Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
  # Definición do router-firewall FW
    config.vm.define "fw" do |fw|
      fw.vm.hostname = "FW"
      fw.vm.network "public_network", bridge: "wlp4s0", ip: "192.0.2.254", netmask: "255.255.255.0"
      fw.vm.network "private_network", ip: "192.168.56.254", netmask: "255.255.255.0"
      # eliminar default gw da rede NAT creada por defecto
      fw.vm.provision "shell",
          run: "always",
          inline:  "ip route del default"    
      # default router
      fw.vm.provision "shell",
          run: "always",
          inline: "ip route add default via 192.0.2.211"
      fw.vm.provider "virtualbox" do |vb|
          vb.name = "FW"
          vb.gui = true
          vb.memory = "1024"
          vb.cpus = 1
          vb.linked_clone = true
          vb.customize ["modifyvm", :id, "--groups", "/FW-Server"]
      end
    end
  
  # Definición do servidor interno server
    config.vm.define "server" do |server|
      server.vm.hostname = "server"
      server.vm.network "private_network", ip: "192.168.56.253", netmask: "255.255.255.0"
      server.vm.synced_folder "./www", "/vagrant_www"
      server.vm.provision "shell", path: "apache.sh"
      # eliminar default gw da rede NAT creada por defecto
      server.vm.provision "shell",
          run: "always",
          inline:  "ip route del default"   
      # default router
      server.vm.provision "shell",
          run: "always",
          inline: "ip route add default via 192.168.56.254"
      server.vm.provider "virtualbox" do |vb|
          vb.name = "server"
          vb.gui = true
          vb.memory = "1024"
          vb.cpus = 2
          vb.linked_clone = true
          vb.customize ["modifyvm", :id, "--groups", "/FW-Server"]
      end
    end
  end
  