Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "web"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 443, host: 4430
    config.vm.provider "virtualbox" do |vb|
       vb.name = "web"
       vb.gui = true
       vb.memory = "1024"
       vb.cpus = 2
       vb.linked_clone = true
    end
    config.vm.synced_folder "./www", "/vagrant_www"
    config.vm.provision "shell", path: "lamp.sh"
    config.vm.post_up_message = "Para acceder executa vagrant ssh"
  end