Vagrant.configure("2") do |config|
    config.vm.box = "debian"
    config.vm.define "tarefa02-exercicio00"  
    config.vm.provision "shell", inline: <<-SHELL
       apt-get update
       apt-get install -y apache2
   SHELL
 end