IMAGE_NAME = "ubuntu/bionic64"
N = 3
Vagrant.configure("2") do |config|
    
    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
                node.vm.box = IMAGE_NAME
                node.vm.hostname = "node-#{i}"
                node.vm.network :private_network, ip: "192.168.10.#{10+i}"
                
                node.vm.provider "virtualbox" do |v|
                        v.memory = 1024
                end
        end
    end
end


  