Vagrant.configure("2") do |config|


  config.vm.define "win-proxmox" do |subconfig|
    subconfig.vm.box = "gusztavvargadr/windows-10-21h2-enterprise-ltsc"
    subconfig.vm.hostname = "win-01-proxmox"
    #subconfig.vm.network "private_network", ip: "192.168.30.5",  virtualbox__intnet: true, name: "rede01"
    subconfig.vm.network "private_network", ip: "192.168.56.5"
    subconfig.vm.provider :virtualbox do |vb2|
      vb2.name = "win-proxmox3"
      vb2.cpus= "2"
    end
  end

  config.vm.define "proxmox" do |proxmox|
  proxmox.vm.box = "xoan/proxmox-ve_6.4"
 # proxmox.vm.box_version = "4.2"
    proxmox.vm.hostname = 'proxmox'
    proxmox.vm.network "private_network", ip: "192.168.56.24"
    proxmox.vm.network "forwarded_port", guest: 8006, host: 8080
  end


  
end