#-----------------------------------------
# Configuracion servidor GLPI
#-----------------------------------------


Vagrant.configure("2") do |config|
    config.vm.define "glpiv3" do |subconfig|
      subconfig.vm.box = "ubuntu/lunar64"
      subconfig.vm.hostname = "glpiv3"
      #subconfig.vm.network "private_network", ip: "192.168.30.4",  virtualbox__intnet: true, name: "rede01"
      subconfig.vm.network "private_network", ip: "192.168.56.4"
      subconfig.vm.network "forwarded_port", guest: 80, host: 8080
      subconfig.vm.provider :virtualbox do |vb1|
          vb1.name = "glpiv3"
          vb1.cpus= "2"
          vb1.customize ["modifyvm", :id, "--groups", "/glpi-demo"]
      end

      subconfig.vm.provision "shell", inline: <<-SHELL
          RED='\033[0;31m'
          NC='\033[0m' # No Color
          echo  -e "***************** ${RED}glpiv3${NC}*******************";
          sudo apt-get update
          sudo apt install zip -y 
          sudo apt install -y apache2 libapache2-mod-php php-mysql mariadb-server php-mbstring php-curl php-gd php-xml php-intl php-ldap php-apcu php-xmlrpc php-cas php-zip php-bz2
          sudo echo "date.timezone = Europe/Madrid" >> /etc/php/8.1/apache2/php.ini
          cd /var/www/html
          wget https://github.com/glpi-project/glpi/releases/download/10.0.6/glpi-10.0.6.tgz
          tar -xf glpi-10.0.6.tgz
          cd glpi
          sudo chown www-data:www-data . -R

          #Habilitar os modulos77
          sudo a2enmod expires rewrite
          sudo systemctl restart apache2

          #Configuracion BD
          echo  -e "***************** ${RED}Configuracion BD ${NC}*******************";

          #sudo systemctl stop mysql.service
          #sudo systemctl set-environment MYSQLD_OPTS="--skip-networking --skip-grant-tables"
          #sudo systemctl start mysql.service
          #          sudo mysql -u root

          sudo mysqladmin --user=root password ""

          #Creacion BD GLPI
          echo  -e "***************** ${RED}Creacion BD para GLPI ${NC}*******************";
          sudo mysql -u root -e "create database glpi charset utf8mb4 collate utf8mb4_unicode_ci;"          
          sudo mysql -u root -e "create user glpi@localhost identified by 'Password1234';"          
          sudo mysql -u root -e "grant all privileges on glpi.* to glpi@localhost;"
          sudo mysql -u root -e "grant select on mysql.time_zone_name to glpi@localhost;" 


          echo  -e "${RED}***************************************************** ${NC}";
          echo  -e "Para finalizar a instalación accede a:"
          echo  -e "\t http://localhost:8080/glpi/install/install.php"
          echo  -e "Base de datos:"
          echo  -e "\t glpi"
          echo  -e "Usuario da dase de datos:"
          echo  -e "\t glpi"
          echo  -e "Contrasinal do usuario da dase de datos:"
          echo  -e "\t Password1234"

          #>verificacion mysql
          #showdatabases 
          #>Verificar usuarios creados
          # SELECT user FROM mysql.user; 

      SHELL
    end
 
    #-----------------------------------------
    # Configuracion cliente WINDOWS
    #-----------------------------------------
    config.vm.define "win-03-glpi" do |subconfig|
      subconfig.vm.box = "gusztavvargadr/windows-10-21h2-enterprise-ltsc"
      subconfig.vm.hostname = "win-01-glpi"
      #subconfig.vm.network "private_network", ip: "192.168.30.5",  virtualbox__intnet: true, name: "rede01"
      subconfig.vm.network "private_network", ip: "192.168.56.5"
      subconfig.vm.provider :virtualbox do |vb2|
        vb2.name = "win-glpi-v3"
        vb2.cpus= "2"
        vb2.customize ["modifyvm", :id, "--groups", "/glpi-demo"]
      end
    end
 
    config.vm.define "android" do |subconfig|
      subconfig.vm.box = "dictcp/android-x86"
      subconfig.vm.network "private_network", ip: "192.168.56.8"
      subconfig.vm.provider :virtualbox do |vb3|
        vb3.name = "android-glpi-v3"
        vb3.cpus= "2"
        vb3.customize ["modifyvm", :id, "--groups", "/glpi-demo"]
      end
    end
  end
  
  
  